from psycopg2 import connect
from psycopg2 import Error, ProgrammingError


class InvalidRequestError(Exception):
    pass


class DBConnector:

    create_query = 'CREATE TABLE faces (' \
                   'id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,' \
                   'path VARCHR(256),' \
                   'emo_id INT)'

    insert_query = 'INSERT INTO faces (path, emo_id) VALUES (%s, %s) RETURNING id'
    get_query = 'SELECT * FROM faces'

    def __init__(self, config):
        self._dbname = config.get('DB_NAME')
        self._dbuser = config.get('DB_USER')
        self._dbhost = config.get('DB_HOST')
        self._create_table()

    def _db_connect(self):
        return connect(
            dbname=self._dbname,
            user=self._dbuser,
            host=self._dbhost,
        )

    def _create_table(self):
        conn = self._db_connect()
        cursor = conn.cursor()
        try:
            cursor.execute(self.create_query)
            conn.commit()
        except ProgrammingError:
            pass
        finally:
            cursor.close()
            conn.close()

    def add_write(self, path, emo_id):
        conn = self._db_connect()
        cursor = conn.cursor()
        try:
            cursor.execute(self.insert_query, [path, emo_id])
            result = cursor.fetchone()[0]
            conn.commit()
        except Error:
            raise InvalidRequestError
        finally:
            cursor.close()
            conn.close()
        return result

    def get_writes(self):
        conn = self._db_connect()
        cursor = conn.cursor()
        try:
            cursor.execute(self.get_query)
            result = cursor.fetchall()
            conn.commit()
        except Error:
            raise InvalidRequestError
        finally:
            cursor.close()
            conn.close()
        return result
